zexall:
	@go run main.go -autoload -fullspeed -tapfile ../tests/passing/zexall.tap

zexbit:
	@go run main.go -autoload -fullspeed -tapfile ../tests/passing/zexbit.tap

zexdoc:
	@go run main.go -autoload -fullspeed -tapfile ../tests/passing/zexdoc.tap

z80tests:
	@go run main.go -autoload -fullspeed -tapfile ../tests/passing/z80tests.tap
